config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  root 'simple_pages#index'

  get 'simple_pages/about'
  get 'simple_pages/contact'
  post 'simple_pages/thank_you'
  post 'payments/create'
  mount ActionCable.server => '/cable'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hieno</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Special+Elite" rel="stylesheet">
     <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
  <% cache do %>
  <div class="whole-page <%= @homepage ? 'home-page' : '' %>">
  <% end %>
  <% if notice %>
  <p id="notice" class="alert alert-primary"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p id="alert" class="alert alert-primary"><%= alert %></p>
  <% end %>
    <nav class="navbar navbar-expand-md navbar-dark" role="navigation" id="navbar">
     <%= link_to "Berlin Bike", root_path, class: "company", id: "company" %>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>

     <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to('Login', new_user_session_path) %>
        </li>
        <% end %>
         <li class="nav-item"></li>
           <li><%= link_to "About", simple_pages_about_path %></li>
         <li class="nav-item"></li>
           <li><%= link_to "Products", products_path %></li>
         <li class="nav-item"></li>
           <li><%= link_to "Orders", orders_path %></li>
         <li class="nav-item"></li>
           <li><%= link_to "Contact", simple_pages_contact_path %></li>  
       </ul>

        <%= form_with(url: products_path, method: 'get', local: true, class: "form-inline my-2 my-lg-0") do |form| %>
        <%= form.text_field :q, id: 'q', value: params[:q], class: "form-control mr-sm-2" %>
        <%= form.submit 'SEARCH', class: 'btn btn-default search-button' %>
        <% end %>
      </div>
    </nav>
    <div class="page-wrap">
      <%= yield %>
    </div>

    <footer class="site-footer">
      &copy; 2019 Berlin Bike
    </footer>
  </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>